### ISSUE TITLE
Refine UI error in Recompile

### ISSUE THREAD

**Issue by violent01** [cydh/rathena#18]
* **rAthena Hash**:  Latest

* **Client Date**: 20180621

* **Server Mode**: Renewal

* **Description of Issue**: Error in recompile
  * Result: setd_sub identifier not found in script.cpp and bool_script_get_constant(constant char*,int64*)': cannot convert argument from 'int *' to 'int64 *' in status.cpp
  * Expected Result: 
  * How to Reproduce:  get the latest rathena then patch this PR then compile and the error shows in script.cpp and status.cpp

* **Modifications that may affect results**: none

**Comment by LordWhiplash** [comment]
i'm having the same problems =c

![image](https://user-images.githubusercontent.com/62680611/78949133-104c9880-7aa1-11ea-815f-5d363ef5aa82.png)

**Comment by sgsilva** [comment]
make[1]: Entering directory `/home/emulador/src/char'
        LD      char-server
make[1]: Leaving directory `/home/emulador/src/char'
make[1]: Entering directory `/home/emulador/src/map'
        CXX     script.cpp
script.cpp: In function ‘int buildin_getblacksmithblessing(script_state*)’:
script.cpp:24576:77: error: ‘setd_sub’ was not declared in this scope
   setd_sub(st, NULL, name, 0, (void*)__64BPRTSIZE((int)bb.nameid), data->ref);
                                                                             ^
script.cpp:24580:80: error: ‘setd_sub’ was not declared in this scope
   setd_sub(st, NULL, ".@refinebb", 0, (void*)__64BPRTSIZE((int)bb.nameid), NULL);
                                                                                ^
make[1]: *** [obj/script.o] Error 1
make[1]: Leaving directory `/home/emulador/src/map'

**Comment by IchigoHikariRO** [comment]
I have the same problem.
Any possible solution?

![image](https://user-images.githubusercontent.com/62913518/80011583-5c013800-84cc-11ea-8f60-be23710f2d7b.png)

**Comment by cydh** [comment]
fxd
